language: node_js

node_js:
  - 10

before_script:
  - echo "Start CI"

install:
  - yarn install --check-files

script:
  - yarn run lint

deploy:
  provider: npm
  email: $NPM_AUTHOR_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
